import { Metadata } from 'next';
import ArticleClient from './ArticleClient';

interface ArticlePageProps {
  params: { slug: string };
}

// Server component that generates metadata
export async function generateMetadata({ params }: ArticlePageProps): Promise<Metadata> {
  const { slug } = params;
  
  try {
    // Fetch article data
    const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL || 'https://unjica.com'}/api/art-digest?slug=${slug}`, { next: { revalidate: 60 } });
    const data = await response.json();
    
    if (!data.article) {
      return {
        title: 'Article Not Found',
        description: 'The requested article could not be found.'
      };
    }
    
    const article = data.article;
    
    return {
      title: article.title,
      description: article.summary,
      openGraph: {
        title: article.title,
        description: article.summary,
        url: `${process.env.NEXT_PUBLIC_BASE_URL || 'https://unjica.com'}/art-news/digest/${article.slug || slug}`,
        siteName: 'AI Art Digest',
        images: article.imageUrl ? [
          {
            url: article.imageUrl,
            width: 1200,
            height: 630,
            alt: article.title,
          }
        ] : [],
        locale: 'en_US',
        type: 'article',
      },
      twitter: {
        card: 'summary_large_image',
        title: article.title,
        description: article.summary,
        images: article.imageUrl ? [article.imageUrl] : [],
      }
    };
  } catch (error) {
    console.error('Error generating metadata:', error);
    
    return {
      title: 'AI Art Digest',
      description: 'Latest art news and insights generated by AI.'
    };
  }
}

// Server component that renders the client component
export default function ArticlePage({ params }: ArticlePageProps) {
  return <ArticleClient slug={params.slug} />;
} 