import { ImageResponse } from 'next/og';

export const runtime = 'edge';

export const alt = 'AI Art Digest';
export const size = {
  width: 1200,
  height: 630,
};
export const contentType = 'image/png';

export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          fontSize: 48,
          background: 'linear-gradient(to right, #3b82f6, #8b5cf6)',
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: 32,
          textAlign: 'center',
          color: 'white',
        }}
      >
        <div style={{ fontSize: 64, fontWeight: 'bold', marginBottom: 24 }}>
          AI Art Digest
        </div>
        <div style={{ fontSize: 32 }}>
          Latest art news and insights generated by AI
        </div>
      </div>
    ),
    { ...size }
  );
} 